apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kong
  name: kong
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
        app: external
    spec:
      containers:
      - name: kong
        image: dojot/kong:latest
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "postgres"
        - name: KONG_PG_USER
          value: "postgres"
        # TODO: Get this from a secret
        - name: KONG_PG_PASSWORD
          value: "kong"
        ports:
        - containerPort: 8000
        - containerPort: 8443
        - containerPort: 8001
        volumeMounts:
        - mountPath: /plugins/pep-kong
          name: pep-kong-plugin
        - mountPath: /plugins/ma-plugin
          name: ma-plugin
      restartPolicy: Always
      volumes:
      - name: pep-kong-plugin
        gitRepo:
          repository: "https://github.com/dojot/pep-kong.git"
          revision: "master"
      - name: ma-plugin
        gitRepo:
          repository: "https://github.com/dojot/ma-kong-plugin.git"
          revision: "master"
