apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kong
  name: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
        app: external
    spec:
      containers:
      - env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: postgres
        image: kong:0.11
        name: kong
        ports:
        - containerPort: 8000
        - containerPort: 8443
        - containerPort: 8001
      restartPolicy: Always
status: {}
