apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrate
  namespace: dojot
spec:
  template:
    metadata:
      name: kong-migrate
    spec:
      containers:
      - name: kong-migrate
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: postgres
        - name: KONG_PG_USER
          value: postgres
        # TODO: Get this value from a secret
        - name: KONG_PG_PASSWORD
          value: kong
        image: kong:0.11
        args: ["kong",  "migrations", "up"]
      restartPolicy: OnFailure