apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: auth
  name: auth
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
      - image: dojot/auth:latest
        name: auth
        env:
        - name: AUTH_DB_HOST
          value: postgres
        - name: AUTH_DB_USER
          value: postgres
        - name: AUTH_DB_PWD
        # TODO: Set this as a secret
          value: kong
        - name: AUTH_KONG_URL
          value: http://kong:8001
        - name: AUTH_CACHE_NAME
          value: "redis"
        - name: AUTH_CACHE_HOST
          value: "localhost"
        # TODO: All email data should be set as secrets
        - name: AUTH_EMAIL_HOST
          value: "smtp.email.com.br"
        - name: AUTH_EMAIL_USER
          value: "username@email.com.br"
        - name: AUTH_EMAIL_PASSWD
          value: "password"
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
