apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: auth
  name: auth
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
      - image: dojot/auth:latest
        name: auth
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PWD
        # TODO: Set this as a secret
          value: kong
        - name: KONG_URL
          value: http://kong:8001
      restartPolicy: Always
