---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin-user
spec:
  template:
    metadata:
      name: create-admin-user
    spec:
      containers:
      - name: create-admin-user
        image: byrnedo/alpine-curl
        volumeMounts:
        - mountPath: /config_file
          name: create-admin
        command: ['/bin/sh', '/config_file/create-admin-user.sh']
      restartPolicy: OnFailure
      volumes:
      - name: create-admin
        configMap:
          name: create-admin-user
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-route-config
spec:
  template:
    metadata:
      name: kong-route-config
    spec:
      containers:
      - name: kong-route-config
        image: byrnedo/alpine-curl
        volumeMounts:
        - mountPath: /config_file
          name: kong-route-config
        command: ['/bin/sh', '/config_file/kong.config.sh']
      restartPolicy: OnFailure
      volumes:
      - name: kong-route-config
        configMap:
          name: kong-route-config
