apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin-user
  namespace: dojot
spec:
  template:
    metadata:
      name: create-admin-user
    spec:
      containers:
      - name: create-admin-user
        image: byrnedo/alpine-curl
        volumeMounts:
        - mountPath: /config_file
          name: create-admin
        command: ['/bin/sh', '/config_file/create-admin-user.sh']
      restartPolicy: OnFailure
      volumes:
      - name: create-admin
        configMap:
          name: create-admin-user

