apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: device-manager
  name: device-manager
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: device-manager
    spec:
      containers:
      - image: dojot/device-manager:latest
        name: device-manager
      restartPolicy: Always
