apiVersion: v1
kind: Service
metadata:
  labels:
    name: gui
  name: gui
  namespace: dojot
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    name: gui
