apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: gui
  name: gui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: gui
    spec:
      containers:
      - image: dojot/gui:latest
        name: gui
        resources: {}
      restartPolicy: Always
