apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: gui
  name: gui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: gui
    spec:
      containers:
      - image: dojot/gui:latest
        name: gui
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gui
  name: gui
spec:
  ports:
  - name: "http"
    port: 80 
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    name: gui
status:
  loadBalancer: {}
