apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-server
  name: kafka-server
  namespace: dojot
spec:
  ports:
  - name: "kafka-server"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka-server
