apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - image: mongo:3.2
        name: mongodb
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
  name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongodb
status:
  loadBalancer: {}
