apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dojot
spec:
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: mongodb
          image: mongo:3.2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "name=mongodb"
            - name: KUBE_NAMESPACE
              value: dojot
      serviceAccountName: mongodb
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
      namespace: dojot
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dojot
      resources:
        requests:
          storage: 1Gi
