apiVersion: v1
kind: Service
metadata:
  labels:
    name: mqtt
  name: mqtt
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "8883"
    port: 8883
    targetPort: 8883
  selector:
    name: mqtt