apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mqtt
  name: mqtt
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mqtt
        app: external-mqtt
    spec:
      containers:
      # TODO: Change the image to dojot/mqtt-manager for TLS support
      - image: ansi/mosquitto
        name: mqtt
        ports:
        # TODO: Change the port to 8883 for TLS support
        - containerPort: 1883
      restartPolicy: Always
      # TODO: Add configuration file volume for TLS support
