apiVersion: v1
kind: Service
metadata:
  labels:
    name: mqtt
  name: mqtt
  namespace: dojot
spec:
  # TODO: Change the port to 8883 for TLS support
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  selector:
    name: mqtt