apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mqtt
  name: mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mqtt
        app: external
    spec:
      containers:
      - image: ansi/mosquitto
        name: mqtt
        ports:
        - containerPort: 1883
        - containerPort: 8883
      restartPolicy: Always
