apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: orion
  name: orion
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orion
    spec:
      containers:
      - args:
        - -dbhost
        - mongodb
        image: dojot/fiware-orion:latest
        name: orion
        ports:
        - containerPort: 1026
      restartPolicy: Always
