apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: pdp-ws
  name: pdp-ws
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: pdp-ws
    spec:
      containers:
      - image: dojot/pdp-ws:latest
        name: pdp-ws
        ports:
        - containerPort: 9763
        volumeMounts:
        - mountPath: /opt/jboss/wildfly/standalone/configuration/
          name: pdp-ws-jboss-config
      restartPolicy: Always
      volumes:
      - name: pdp-ws-jboss-config
        configMap:
          name: pdp-ws-jboss-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pdp-ws
  name: pdp-ws
spec:
  ports:
  - name: "9763"
    port: 9763
    targetPort: 9763
  selector:
    name: pdp-ws

