apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        image: postgres:9.4
        name: postgres
        resources: {}
        volumeMounts:
          - name: postgres-volume
            mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: postgres-volume
          rbd:
            monitors: [CEPH_MONITORS]
            pool: rbd
            image: postgres-volume
            fsType: xfs
            readOnly: false
            user: admin
            keyring: /etc/ceph/ceph.client.admin.keyring
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres