apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        image: postgres:9.4
        name: postgres
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres
status:
  loadBalancer: {}
