apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-sentinel
  name: redis-sentinel
  namespace: dojot
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
