apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
  namespace: dojot
spec:
  replicas: 3
  selector:
    redis-sentinel: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
    spec:
      containers:
      - name: redis-sentinel
        image: kubernetes/redis:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
