apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dojot
provisioner: ceph.com/rbd
parameters:
  monitors: [CEPH_MONITORS]
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  pool: kube
  userId: kube
  userSecretName: ceph-secret-user
  imageFormat: "2"
  imageFeatures: layering
